name: Deploy to Github Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

  # To manually trigger a workflow, use the workflow_dispatch event. You can manually trigger a workflow run using the GitHub API, GitHub CLI, or GitHub browser interface. For more information, see "Manually running a workflow."
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install node
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2

      - name: build
        run: |
          pnpm install
          pnpm run build
          pnpm run export
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
